# Generated by Django 2.2.13 on 2022-12-17 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='task_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 17, 11, 8, 23, 76710, tzinfo=utc), null=True),
        ),
    ]
