# Generated by Django 2.2.13 on 2022-12-25 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221224_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myalbum',
            name='images',
        ),
        migrations.AddField(
            model_name='myalbum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myimages'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='task_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 25, 2, 53, 50, 930165, tzinfo=utc), null=True),
        ),
        migrations.DeleteModel(
            name='AlbumPhotos',
        ),
    ]
